try-catch-finally句内のreturnについて    [suggested]
web link: https://qiita.com/eijenson/items/7e9e112e69b37f72353c

i.e.
try-catch-finally句の中で、returnをする場合、
finally句を設定するとreturnする前にかならずfinally句の中が実行される。




Try-catch-finally-return clarification [duplicate]
web link: https://stackoverflow.com/questions/15225819/try-catch-finally-return-clarification



















